---
- name: Create heimdall directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ hive_user }}"
    group: "{{ hive_user }}"
    mode: 0755
  with_items:
    - /docker/heimdall

- name: heimdall Docker Container
  docker_container:
    name: heimdall
    image: linuxserver/heimdall
    pull: true
    volumes:
      - /docker/heimdall:/config
      - /docker/shared:/shared
    ports:
      - "{{ heimdall_port }}:80/tcp"
    env:
      TZ: "{{ timezone }}"
      PUID: "{{ hive_uid | string }}"
      PGID: "{{ hive_gid | string }}"
    restart_policy: unless-stopped
