---
- name: create gocontrol mapping
  template:
    src: 99-husbzb-1.rules.j2
    dest: /etc/udev/rules.d/99-husbzb-1.rules
    owner: root
    group: root
    mode: 0644
  notify: update device rules
