global_modules:
  - sentry

sentry:
  module: sentry
  class: Sentry
  dsn: !secret sentry_dsn

power_usage_washer:
  module: power_usage
  class: PowerUsageAlert
  dependencies: sentry
  entity_id: sensor.washer_power
  delay: 3
  input_boolean: input_boolean.washer
  notify:
    - telegram_household
  sonos:
    - media_player.office
    - media_player.kitchen
  done_message: "The wash machine has finished"

power_usage_dryer:
  module: power_usage
  class: PowerUsageAlert
  dependencies: sentry
  entity_id: sensor.dryer_power
  delay: 3
  input_boolean: input_boolean.dryer
  notify:
    - telegram_household
  sonos:
    - media_player.office
    - media_player.kitchen
  done_message: "The dryer has finished"

garage_motion_overnight:
  module: generic_alert
  class: GenericAlert
  dependencies: sentry
  entity_id: sensor.garage_multisensor_burglar
  input_boolean: input_boolean.garage_motion
  state:
    - 3
    - 8
  tod:
    after: "00:00:00"
    before: "07:00:00"
  message: '{{now().strftime("%H:%M:%S %Y-%m-%d")}}: Garage motion detected {{ relative_time(states.sensor.garage_multisensor_burglar.last_changed) }} ago.'
  camera: camera.garage
  camera_output: "/downloads/cameras/garage_{alert_id}.jpg"
  repeat:
    - 5
  telegram:
    - !secret telegram_group_id_home

garage_door_alert:
  module: generic_alert
  class: GenericAlert
  dependencies: sentry
  entity_id: cover.garage_door
  # should account for camera lag
  delay: 3
  input_boolean: input_boolean.garage_door
  state: open
  # TODO: support ack
  message: '{{now().strftime("%H:%M:%S %Y-%m-%d")}}: Garage door open for {{ relative_time(states.cover.garage_door.last_changed) }}. /closeGarage /ackGarage'
  done_message: '{{now().strftime("%H:%M:%S %Y-%m-%d")}}: Garage has been closed.'
  camera: camera.garage
  camera_output: "/downloads/cameras/garage_{alert_id}.jpg"
  repeat:
    - 5
    - 30
    - 60
  can_acknowledge: true
  ack_command: "/ackGarage"
  skip_first: true
  telegram:
    - !secret telegram_group_id_home

alarm_manager:
  module: alarm_manager
  class: AlarmManager
  dependencies: sentry
  alarm: alarm_control_panel.home
  telegram:
    - !secret telegram_group_id_home
  reminder_time: "23:45:00"
  deactivate_time: "07:00:00"
  activation_delay: 15
