---
galaxy_info:
  author: Werner Dijkerman
  description: Installing and configuring Telegraf
  company: myCompany.Dotcom
  license: MIT
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: opensuse
      versions:
        - all
    - name: Windows
      versions:
        - all

  galaxy_tags:
    - monitoring

dependencies: []
