---
sudo: required
language: python
services:
  - docker

install:
  - curl -sSlo requirements.txt https://raw.githubusercontent.com/dj-wasabi/ansible-ci-base/master/requirements.txt
  - pip install -r requirements.txt

script:
  - molecule --version
  - ansible --version
  - molecule test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
