alias: "Doorbell Chime"
initial_state: true
trigger:
  platform: state
  entity_id: binary_sensor.doorbell_doorbell
  to: 'on'
action:
  service: script.alexa_announce
  data:
    message: <audio src="https://s3.amazonaws.com/tsatsatzu-alexa/sound/tech/DOORBELL.mp3"/>
