- url: /local/plugins/auto-entities.js?v=1
  type: module
- url: /local/community/lovelace-nextbus-card/nextbus-card.js?v=2
  type: module
- url: /local/community/lovelace-recology-card/recology-card.js?v=2
  type: module
- url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
  type: module
- url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
  type: module
- url: /hacsfiles/group-card/group-card.js
  type: module
