title: Master Bedroom
id: master-bedroom
path: master-bedroom
icon: mdi:bed-king
cards:
  # - type: sensor
  #   entity: sensor.master_bedroom_temperature
  #   graph: line
  #   detail: 1
  #   hours_to_show: 48
  # - type: sensor
  #   entity: sensor.master_bedroom_humidity
  #   graph: line
  #   detail: 1
  #   hours_to_show: 48
  - type: entities
    entities:
      - fan.master_bedroom
  - type: custom:group-card
    card:
      type: entities
      title: "Lights"
      show_header_toggle: true
    group: group.master_bedroom_lights
  - type: custom:mini-media-player
    entity: media_player.master_bedroom
