title: Media
id: media
path: media
icon: mdi:music
cards:
  - type: custom:mini-media-player
    entity: media_player.office
    # source: icon
    # hide:
    #   power: true
    #   icon: true
    #   source: true
    speaker_group:
      platform: sonos
      show_group_count: true
      entities:
        - entity_id: media_player.office
          name: Office
        - entity_id: media_player.kitchen
          name: Kitchen

    shortcuts:
      columns: 4 # Max buttons per row
      buttons:
        - icon: mdi:cat
          type: playlist
          name: Discovery Weekly
          id: spotify:user:spotify:playlist:37i9dQZEVXcHXmvZsLUc4h
        - icon: mdi:cat
          type: playlist
          name: Something
          id: spotify:playlist:37i9dQZF1E8Em65iz7xPwH
