- alias: "Set theme at startup"
  trigger:
    platform: homeassistant
    event: start
  action:
    service: frontend.set_theme
    data:
      name: synthwave

# - alias: "Set theme for day and night"
#   trigger:
#     - platform: homeassistant
#       event: start
#     - platform: state
#       entity_id: sun.sun
#       to: above_horizon
#     - platform: state
#       entity_id: sun.sun
#       to: below_horizon
#   action:
#     - service_template: frontend.set_theme
#       data_template:
#         name: >
#           {% if states.sun.sun.state == "above_horizon" %}
#             Google - Light
#           {% else %}
#             Google - Dark
#           {% endif %}

# {'message_id': 171, 'date': 1578624944, 'chat': {'id': -313131514, 'type': 'group', 'title': 'Home', 'all_members_are_administrators': True}, 'entities': [], 'caption_entities': [], 'photo': [], 'new_chat_members': [{'id': 850525420, 'first_name': 'Red Queen', 'is_bot': True, 'username': 'Hive4332Bot'}], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'from': {'id': 958786881, 'first_name': 'David', 'is_bot': False, 'last_name': 'Cramer', 'language_code': 'en'}}

- alias: "Telegram bot that reply pong to ping"
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: "/ping"
  action:
    - service: telegram_bot.send_message
      data_template:
        target: "{{ trigger.event.data.chat_id }}"
        message: "pong"

- id: replyAckGarage
  alias: "Telegram bot to ack the garage door being open"
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: "/ackGarage"
  action:
    - service: alert.turn_off
      entity_id: alert.garage_door_open

- id: replyCloseGarage
  alias: "Telegram bot to close the garage door"
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: "/closeGarage"
  action:
    - service: cover.close_cover
      entity_id: cover.garage_door

- id: replyAckStorage
  alias: "Telegram bot to ack the garage storage being unlocked"
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: "/ackStorage"
  action:
    - service: alert.turn_off
      entity_id: alert.garage_door_unlocked

- id: replyLockStorage
  alias: "Telegram bot to lock the garage storage"
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: "/lockStorage"
  action:
    - service: lock.lock
      entity_id: lock.garage_storage_deadbolt

- id: replyAckAlarm
  alias: "Telegram bot to ack the alarm being unarmed"
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: "/ackAlarm"
  action:
    - service: alert.turn_off
      entity_id: alert.alarm_not_armed

- alias: "Sync Tasmota states on start-up - autodiscovery"
  initial_state: true
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: "cmnd/tasmotas/state"
        payload: ""

- alias: "Enable overnight alerts"
  trigger:
    - platform: state
      entity_id: binary_sensor.is_overnight
      to: "on"
  action:
    - service: homeassistant.turn_on
      entity_id: alert.garage_motion_late_night

- alias: "Disable overnight alerts"
  trigger:
    - platform: state
      entity_id: binary_sensor.is_overnight
      to: "on"
  action:
    - service: homeassistant.turn_off
      entity_id: alert.garage_motion_late_night

- id: master_bedroom_aqara_switch_one_single
  alias: Master Bedroom - Switch One - Turn On
  trigger:
    - event_data:
        command: "single"
        unique_id: "00:15:8d:00:02:90:14:e9:1:0x0012"
      event_type: zha_event
      platform: event
  action:
    - data:
        entity_id: group.master_bedroom_lights
      service: homeassistant.turn_on

- id: master_bedroom_aqara_switch_one_double
  alias: Master Bedroom - Switch One - Bedtime
  trigger:
    - event_data:
        command: "double"
        unique_id: "00:15:8d:00:02:90:14:e9:1:0x0012"
      event_type: zha_event
      platform: event
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.bedtime

- id: master_bedroom_aqara_switch_one_hold
  alias: Master Bedroom - Switch One - All Lights Off
  trigger:
    - event_data:
        command: "hold"
        unique_id: "00:15:8d:00:02:90:14:e9:1:0x0012"
      event_type: zha_event
      platform: event
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.lights_off

- id: master_bedroom_aqara_switch_two_single
  alias: Master Bedroom - Switch Two - Toggle
  trigger:
    - event_data:
        command: "single"
        unique_id: "00:15:8d:00:02:8f:4c:98:1:0x0012"
      event_type: zha_event
      platform: event
  action:
    - data:
        entity_id: group.master_bedroom_lights
      service: homeassistant.toggle

- id: master_bedroom_aqara_switch_two_double
  alias: Master Bedroom - Switch Two - Bedtime
  trigger:
    - event_data:
        command: "double"
        unique_id: "00:15:8d:00:02:8f:4c:98:1:0x0012"
      event_type: zha_event
      platform: event
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.bedtime

- id: master_bedroom_aqara_switch_two_hold
  alias: Master Bedroom - Switch Two - All Lights Off
  trigger:
    - event_data:
        command: "hold"
        unique_id: "00:15:8d:00:02:8f:4c:98:1:0x0012"
      event_type: zha_event
      platform: event
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.lights_off
