default_config:

homeassistant:
  name: Home
  latitude: !secret lat
  longitude: !secret lng
  elevation: 92
  time_zone: America/Los_Angeles
  unit_system: imperial
  packages: !include_dir_named packages/
  customize: !include customize.yaml
  allowlist_external_dirs:
    - /downloads

group: !include groups.yaml
automation: !include_dir_list automations/
script: !include_dir_named scripts/
frontend: !include frontend.yaml
http: !include http.yaml
recorder: !include recorder.yaml
person: !include persons.yaml
sensor: !include_dir_merge_list sensors/
switch: !include switches.yaml
zone: !include zones.yaml
alert: !include_dir_named alerts/
scene: !include_dir_list scenes/

lovelace:
  mode: yaml

updater:
  reporting: true
  include_used_components: true

downloader:
  download_dir: /downloads

cloud:
  alexa:
    filter:
      include_entities:
        # - lock.garage_storage_deadbolt
        - cover.garage_door
        - input_boolean.dryer
        - input_boolean.washer
        - scene.bedtime
        - scene.lights_out
        - scene.movie_time
        - script.turntable
        - switch.pi_hole
        - switch.master_bedroom_vornado_fan
      exclude_entities:
        # remove all light groups as it confuses Alexa
        - light.all_lights
        - light.master_bedroom_lights
        - light.guest_bedroom_lights
        - light.hallway_lights
        - light.office_lights
        - light.media_room_lights
        - light.garage_lights
        - light.exterior_lights
        - light.dining_room_lights
        - light.kitchen_lights
        - light.entrance_lights
        - light.front_door_lights
        - light.back_yard_lights
        # this is remapped as a fan
        - light.guest_bedroom_office_room_fan
        - light.back_stairs_lights
      include_domains:
        - light
        - fan
        - media_player
        # - lock
        # - camera
    entity_config:
      switch.master_bedroom_vornado_fan:
        display_categories: FAN
      light.guest_bedroom_office_room_fan:
        display_categories: FAN
  google_actions:
    filter:
      include_entities:
        # - lock.garage_storage_deadbolt
        - cover.garage_door
        - input_boolean.dryer
        - input_boolean.washer
        - switch.pi_hole
        - switch.master_bedroom_vornado_fan
        - script.turntable
      include_domains:
        - light
        - fan
        - media_player
        # - fan
        # - lock
        # - camera
      # exclude_entities:
      #   - lock.2018_jeep_wrangler_lock
    entity_config:
      camera.garage_exterior:
        room: Front Exterior
      camera.front_door_exterior:
        room: Front Exterior
      lock.garage_storage_deadbolt:
        room: Garage
      camera.garage:
        room: Garage
      camera.media_room:
        room: Media Room
      cover.garage_door:
        room: Garage
      input_boolean.dryer:
        room: Garage
      input_boolean.washer:
        room: Garage
      media_player.garage:
        room: Garage
      # fan.master_bedroom:
      #   room: Master Bedroom
      light.master_bedroom_bedroom_center_cans:
        room: Master Bedroom
      light.master_bedroom_bedroom_side_cans:
        room: Master Bedroom
      light.master_bedroom_bedroom_sitting_cans:
        room: Master Bedroom
      light.master_bedroom_master_bed_hallway_cans:
        room: Master Bedroom
      switch.master_bedroom_vornado_fan:
        room: Master Bedroom
      media_player.master_bedroom:
        room: Master Bedroom
      light.guest_bedroom_guest_bedroom_cans:
        room: Guest Bedroom
      light.guest_bedroom_guest_bedroom_wall:
        room: Guest Bedroom
      light.guest_bedroom_office_fire_place_cans:
        room: Office
      light.guest_bedroom_office_room_center_light:
        room: Office
      light.guest_bedroom_office_room_wall_cans:
        room: Office
      light.guest_bedroom_office_room_fan:
        room: Office
      media_player.office:
        room: Office
      light.back_stairs_kitchen_cans:
        room: Kitchen
      media_player.kitchen:
        room: Kitchen
      light.guest_bedroom_dining_room_cans:
        room: Dining Room
      light.guest_bedroom_dining_room_center:
        room: Dining Room
      light.guest_bedroom_hallway_lights:
        room: Hallway
      light.garage_bottom_of_stairs:
        room: Entrance

zwave:
  # usb_path: /dev/ttyACM0
  usb_path: /dev/ttyUSB0
  network_key: "0x50, 0x78, 0x13, 0x63, 0x55, 0x17, 0x65, 0xAB, 0xC9, 0x54, 0x9C, 0xDB, 0x1B, 0xED, 0x0F, 0x86"

zha:
  # configured in UI now
  # radio_type: ezsp
  # usb_path: /dev/ttyUSB1
  database_path: /config/zigbee.db

# zigbee:
#   device: /dev/ttyUSB2

stream:

weather:
  - platform: darksky
    api_key: !secret darksky_key
    mode: daily
    name: "San Francisco, CA"

plex:
  host: !secret plex_host
  port: !secret plex_webui_port
  token: !secret plex_token

geofency:

speedtestdotnet:
  monitored_conditions:
    - download
    - upload

tts:
  - platform: google_translate
    service_name: google_say
    cache: true
    cache_dir: /tts-cache
    time_memory: 300

# influxdb:
#   host: influxdb
#   port: !secret influxdb_port
#   database: hass

# image_processing: !include image_processing.yaml

binary_sensor: !include binary_sensors.yaml

# Device Tracking

# unifi:
#   controllers:
#     - host: !secret unifi_host
#       site: "Default"
#       dont_track_wired_clients: true
#       dont_track_devices: true

device_tracker:
  - platform: tile
    username: !secret tile_username
    password: !secret tile_password

# dyson:
#   username: !secret dyson_username
#   password: !secret dyson_password
#   language: US
#   devices:
#     - device_id: !secret dyson_fan_id
#       device_ip: !secret dyson_fan_host

input_text:
  recology_api_url:
    initial: !secret recology_api_url

telegram_bot:
  - platform: polling
    api_key: !secret telegram_token
    allowed_chat_ids:
      - !secret telegram_chat_id_david
      - !secret telegram_chat_id_sukhpreet
      - !secret telegram_group_id_home

notify:
  - name: telegram_david
    platform: telegram
    chat_id: !secret telegram_chat_id_david
  - name: telegram_sukhpreet
    platform: telegram
    chat_id: !secret telegram_chat_id_sukhpreet
  # https://stackoverflow.com/questions/45414021/get-telegram-channel-group-id/45577773#45577773
  - name: telegram_household
    platform: telegram
    chat_id: !secret telegram_group_id_home
  # - name: garage_alert
  #   platform: group
  #   services:
  #     - service: camera.snapshot
  #       data:
  #         entity_id: camera.garage
  #         filename: "/downloads/cameras/garage_latest.jpg"
  #     - service: notify.telegram_david

# custom components
# "Restart HA one time before adding it to config."
# radarr_upcoming_media:
# sonarr_upcoming_media:
hacs:
  token: !secret hacs_github_token

# media_player:
#   - platform: spotify
#     client_id: !secret spotify_client_id
#     client_secret: !secret spotify_client_secret

# appdaemon:

# hadashboard:
#   dash_url: http://192.168.1.25:5050

mqtt:
  broker: !secret mqtt_host
  port: !secret mqtt_port
  client_id: home-assistant-1
  keepalive: 60
  protocol: 3.1
  birth_message:
    topic: tele/hass1/LWT
    payload: Online
    qos: 1
    retain: false
  will_message:
    topic: tele/hass1/LWT
    payload: Offline
    qos: 1
    retain: false
  # discovery: true
  # discovery_prefix: homeassistant

input_boolean:
  garage_motion:
    name: "Garage Motion"
    initial: off
    icon: mdi:garage
  garage_door:
    name: "Garage Door"
    initial: off
    icon: mdi:garage
