---
- name: minecraft (java) Docker Container
  docker_container:
    name: minecraft
    image: itzg/minecraft-server:latest
    pull: true
    restart_policy: unless-stopped
    volumes:
      - /docker/minecraft/data/valhesia:/data
      - /docker/minecraft/modpacks:/modpacks:ro
    ports:
      - "25565:25565/tcp"
      - "25575:25575/tcp"
      # - "8123:8123/tcp"
    env:
      EULA: "TRUE"
      GAMEMODE: "{{ minecraft_gamemode }}"
      DIFFICULTY: "{{ minecraft_difficulty }}"
      MOTD: "{{ minecraft_server_name }}"
      MAX_PLAYERS: "{{ minecraft_max_players }}"
      UID: "{{ hive_uid | string }}"
      GID: "{{ hive_gid | string }}"
      INIT_MEMORY: "1G"
      MAX_MEMORY: "6G"
      REMOVE_OLD_MODS: "true"
      VIEW_DISTANCE: "6"
      OVERRIDE_SERVER_PROPERTIES: "true"
      # ALLOW_FLIGHT: "TRUE"
      # MAX_TICK_TIME: "-1"
      # REPLACE_ENV_VARIABLES: "TRUE"

      # Valhesia
      # TYPE: FORGE
      FORGEVERSION: "31.2.36"
      VERSION: "1.15.2"
      # GENERIC_PACK: "/modpacks/Valhelsia_SERVER-2.2.8.zip"
      TYPE: "CURSEFORGE"
      CF_SERVER_MOD: "/modpacks/Valhelsia_SERVER-2.2.8.zip"
      # Ages
      # TYPE: CURSEFORGE
      # FORGEVERSION: "31.2.33"
      # VERSION: "1.15.2"
      # GENERIC_PACK: "/modpacks/SevTech_Ages_Server_3.1.2-hotfix.1.zip"
      # RLCraft
      # TYPE: "FORGE"
      # VERSION: "1.12.2"
      # FORGEVERSION: "14.23.5.2838"
      # GENERIC_PACK: "/modpacks/RLCraft+Server+Pack+1.12.2+-+Beta+v2.8.2.zip"
