alias: "Media Player all speakers script"
sequence:
  - service: notify.alexa_media
    data_template:
      data:
        type: tts
      message: "{{ message }}"
      target:
        - media_player.echo_flex_dining_room
        - media_player.echo_flex_master_bedroom
