alias: "Sonos Play script"
sequence:
  - service: sonos.snapshot
    data_template:
      entity_id: "{{ entity_id }}"
  - service: sonos.unjoin
    data_template:
      entity_id: "{{ entity_id }}"
  - service: media_player.volume_set
    data_template:
      entity_id: "{{ entity_id }}"
      volume_level: "{{ volume }}"
  - service: media_player.play_media
    data_template:
      entity_id: "{{ entity_id }}"
      media_content_id: "{{ media_content_id }}"
      media_content_type: "music"
  - delay: "{{ delay }}"
  - service: sonos.restore
    data_template:
      entity_id: "{{ entity_id }}"
