---
- name: create panelkit directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ hive_user }}"
    group: "{{ hive_user }}"
    mode: 0755
  with_items:
    - /docker/homeassistant/config/www/panelkit/

- name: check for panelkit cache
  stat:
    path: "/docker/homeassistant/cache/panelkit-{{ panelkit_version }}.html"
  register: panelkit_archive_exist

- name: fetch panelkit
  get_url:
    url: "https://github.com/dcramer/panelkit/releases/download/{{ panelkit_version }}/index.html"
    dest: "/docker/homeassistant/cache/panelkit-{{ panelkit_version }}.html"
    mode: 0644
  when: not panelkit_archive_exist.stat.exists

- name: install panelkit
  copy:
    src: "/docker/homeassistant/cache/panelkit-{{ panelkit_version }}.html"
    dest: /docker/homeassistant/config/www/panelkit/index.html
    remote_src: true
    mode: 0644
    owner: "{{ hive_user }}"
    group: "{{ hive_user }}"

- name: create panelkit config
  template:
    src: "panelkit-config.js.j2"
    dest: "/docker/homeassistant/config/www/panelkit/config.js"
