---
homekit:
  advertise_ip: 192.168.1.25
  port: !secret homekit_port
  filter:
    include_domains:
      # - alarm_control_panel
      - climate
      - camera
      - cover
    exclude_entity_globs:
      # - light.all_*
      - camera.*_person
      - light.guest_bedroom_hallway_lights
      - media_player.*_tv
    include_entities:
      - media_player.office
      - media_player.kitchen
      - media_player.media_room
      - switch.pi_hole
      - switch.master_bedroom_vornado_fan
      - scene.bedtime
      - scene.movie_time
      - scene.dim_hallway
    include_entity_globs:
      - light.*lights
  entity_config:
    alarm_control_panel.home:
      code: !secret simplisafe_code
    media_player.office:
      feature_list:
        - feature: play_pause
        - feature: toggle_mute
    media_player.kitchen:
      feature_list:
        - feature: play_pause
        - feature: toggle_mute
automation:
  - alias: "Start HomeKit"
    trigger:
      - platform: homeassistant
        event: start
    action:
      - wait_template: >-
          {% if not states.media_player.office %}
            false
          {% else %}
            true
          {% endif %}
        timeout: 00:15 # Waits 15 minutes
        continue_on_timeout: false
      - service: homekit.start
