lutron:
  host: !secret lutron_host
  username: !secret lutron_username
  password: !secret lutron_password

group:
  master_bedroom_lights:
    name: Master Bedroom Lights
    entities:
      - light.master_bedroom_bedroom_center_cans
      - light.master_bedroom_bedroom_side_cans
      - light.master_bedroom_bedroom_sitting_cans
      - light.master_bedroom_master_bed_hallway_cans
  guest_bedroom_lights:
    name: Guest Bedroom Lights
    entities:
      - light.guest_bedroom_guest_bedroom_cans
      - light.guest_bedroom_guest_bedroom_wall
  office_lights:
    name: Office Lights
    entities:
      - light.guest_bedroom_office_fire_place_cans
      - light.guest_bedroom_office_room_center_light
      - light.guest_bedroom_office_room_wall_cans
  kitchen_lights:
    name: Kitchen Lights
    entities:
      - light.back_stairs_kitchen_cans
  dining_room_lights:
    name: Dining Room Lights
    entities:
      - light.guest_bedroom_dining_room_cans
      - light.guest_bedroom_dining_room_center
  hallway_lights:
    name: Hallway Lights
    entities:
      - light.guest_bedroom_hallway_lights
  entryway_lights:
    name: Entryway Lights
    entities:
      - light.garage_bottom_of_stairs
  front_door_lights:
    name: Front Door Lights
    entities:
      - light.garage_entry_can
      - light.garage_bottom_of_stairs
