lutron:
  host: !secret lutron_host
  username: !secret lutron_username
  password: !secret lutron_password

light:
  - platform: switch
    name: Garage Main
    entity_id: switch.garage_garage_lights
  - platform: switch
    name: Garage Flourescent
    entity_id: switch.garage_garage_fluorecnet

  - platform: group
    name: Master Bedroom Lights
    entities:
      - light.master_bedroom_bedroom_center_cans
      - light.master_bedroom_bedroom_side_cans
      - light.master_bedroom_bedroom_sitting_cans
      - light.master_bedroom_master_bed_hallway_cans
  - platform: group
    name: Guest Bedroom Lights
    entities:
      - light.guest_bedroom_guest_bedroom_cans
      - light.guest_bedroom_guest_bedroom_wall
  - platform: group
    name: Office Lights
    entities:
      - light.guest_bedroom_office_fire_place_cans
      - light.guest_bedroom_office_room_center_light
      - light.guest_bedroom_office_room_wall_cans
  - platform: group
    name: Kitchen Lights
    entities:
      - light.back_stairs_kitchen_cans
  - platform: group
    name: Dining Room Lights
    entities:
      - light.guest_bedroom_dining_room_cans
      - light.guest_bedroom_dining_room_center
  - platform: group
    name: Hallway Lights
    entities:
      - light.guest_bedroom_hallway_lights
      - light.guest_bedroom_front_staircase_decorative
  - platform: group
    name: Media Room Lights
    entities:
      - light.media_room_media_room_cans
      - light.media_room_seating_area
      - light.garage_media_room_emergency
      - light.media_room_media_room_bike_area
      - light.media_room_garage_hall
      - light.media_room_bar_ligh_undercabinet
      - light.back_stairs_top_of_back_stairs
  - platform: group
    name: Front Door Lights
    entities:
      - light.garage_entry_can
      - light.garage_bottom_of_stairs
      # - light.garage_exterior_scoce
      # - light.garage_garage_door_led

  - platform: group
    name: Garage Lights
    entities:
      - light.garage_fluorescent
      - light.garage_main

  - platform: group
    name: Garage Lights
    entities:
      - light.garage_fluorescent
      - light.garage_main

  # Exterior light groups
  - platform: group
    name: Exterior Lights
    entities:
      - light.media_room_back_yard_landscape
      - light.media_room_media_exterior_sconces
      - light.garage_entry_can
      - light.garage_bottom_of_stairs
      - light.garage_exterior_scoce
      - light.garage_garage_door_led
  - platform: group
    name: Entrance Lights
    entities:
      - light.garage_bottom_of_stairs
  - platform: group
    name: Back Yard Lights
    entities:
      - light.media_room_back_yard_landscape
      - light.media_room_media_exterior_sconces
