---
# sonoff s31 - autodiscovery disabled
switch:
  - platform: mqtt
    name: "Master Bedroom - Vornado Fan"
    state_topic: "tele/master-bedroom-vornado-fan/STATE"
    value_template: "{{ value_json.POWER }}"
    command_topic: "cmnd/master-bedroom-vornado-fan/POWER"
    availability_topic: "tele/master-bedroom-vornado-fan/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false
sensor:
  - platform: mqtt
    name: "Master Bedroom - Vornado Fan - Voltage"
    state_topic: "tele/master-bedroom-vornado-fan/SENSOR"
    value_template: "{{ value_json['ENERGY'].Voltage }}"
    unit_of_measurement: "V"
    availability_topic: "tele/master-bedroom-vornado-fan/LWT"
    qos: 1
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Master Bedroom - Vornado Fan - Current"
    state_topic: "tele/master-bedroom-vornado-fan/SENSOR"
    value_template: "{{ value_json['ENERGY'].Current | round(2) }}"
    unit_of_measurement: "A"
    availability_topic: "tele/master-bedroom-vornado-fan/LWT"
    qos: 1
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Master Bedroom - Vornado Fan - Power"
    state_topic: "tele/master-bedroom-vornado-fan/SENSOR"
    value_template: "{{ value_json['ENERGY'].Power }}"
    unit_of_measurement: "W"
    availability_topic: "tele/master-bedroom-vornado-fan/LWT"
    qos: 1
    payload_available: "Online"
    payload_not_available: "Offline"
    device_class: power
  - platform: mqtt
    name: "Master Bedroom - Vornado Fan - Power Factor"
    state_topic: "tele/master-bedroom-vornado-fan/SENSOR"
    value_template: "{{ value_json['ENERGY'].Factor }}"
    availability_topic: "tele/master-bedroom-vornado-fan/LWT"
    qos: 1
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Master Bedroom - Vornado Fan - Energy Today"
    state_topic: "tele/master-bedroom-vornado-fan/SENSOR"
    value_template: "{{ value_json['ENERGY'].Today }}"
    unit_of_measurement: "kWh"
    availability_topic: "tele/master-bedroom-vornado-fan/LWT"
    qos: 1
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Master Bedroom - Vornado Fan - Energy Yesterday"
    state_topic: "tele/master-bedroom-vornado-fan/SENSOR"
    value_template: "{{ value_json['ENERGY'].Yesterday }}"
    unit_of_measurement: "kWh"
    availability_topic: "tele/master-bedroom-vornado-fan/LWT"
    qos: 1
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Master Bedroom - Vornado Fan - Energy Total"
    state_topic: "tele/master-bedroom-vornado-fan/SENSOR"
    value_template: "{{ value_json['ENERGY'].Total }}"
    unit_of_measurement: "kWh"
    availability_topic: "tele/master-bedroom-vornado-fan/LWT"
    qos: 1
    payload_available: "Online"
    payload_not_available: "Offline"

input_boolean:
  master_bedroom_vornado_fan:
    name: "Master Bedroom - Vornado Fan"
    initial: off
    icon: mdi:fan
