pi_hole:
  - host: !secret pi_hole_host
    api_key: !secret pi_hole_api_key


binary_sensor:
  - platform: command_line
    command: "curl -s http://192.168.1.86/admin/index.php | grep 'color:' | grep 'status' | cut -d ':' -f 2 | cut -d '>' -f 3 | cut -d '<' -f 1 | sed -e 's/^[[:space:]]*//'"
    name: pi_hole_status
    payload_on: "Active"
    payload_off: "Offline"
    scan_interval: 1

switch:
  - platform: template
    switches:
      pi_hole:
        value_template: "{{ is_state('binary_sensor.pi_hole_status', 'on') }}"
        turn_on:
          service: pi_hole.enable
        turn_off:
          service: pi_hole.disable
          data:
            duration: 00:00:60

group:
  pi_hole:
    name: Pi Hole Status
    entities:
      # - sensor.pi_hole_status
      - switch.pi_hole
      - sensor.pi_hole_ads_blocked_today
      - sensor.pi_hole_ads_percentage_blocked_today
      - sensor.pi_hole_dns_queries_cached
      - sensor.pi_hole_dns_queries_forwarded
      - sensor.pi_hole_dns_queries_today
      - sensor.pi_hole_dns_unique_clients
      - sensor.pi_hole_dns_unique_domains
      - sensor.pi_hole_domains_blocked
