# sonoff s31 - autodiscovery disabled
switch:
  - platform: mqtt
    name: "Washer power"
    state_topic: "tele/washer/STATE"
    value_template: "{{ value_json.POWER }}"
    command_topic: "cmnd/washer/POWER"
    availability_topic: "tele/washer/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false
sensor:
  - platform: mqtt
    name: "Washer Voltage"
    state_topic: "tele/washer/SENSOR"
    value_template: "{{ value_json['ENERGY'].Voltage }}"
    unit_of_measurement: "V"
    availability_topic: "tele/washer/LWT"
    qos: 1
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Washer Current"
    state_topic: "tele/washer/SENSOR"
    value_template: "{{ value_json['ENERGY'].Current | round(2) }}"
    unit_of_measurement: "A"
    availability_topic: "tele/washer/LWT"
    qos: 1
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Washer Power"
    state_topic: "tele/washer/SENSOR"
    value_template: "{{ value_json['ENERGY'].Power }}"
    unit_of_measurement: "W"
    availability_topic: "tele/washer/LWT"
    qos: 1
    payload_available: "Online"
    payload_not_available: "Offline"
    device_class: power
  - platform: mqtt
    name: "Washer Power Factor"
    state_topic: "tele/washer/SENSOR"
    value_template: "{{ value_json['ENERGY'].Factor }}"
    availability_topic: "tele/washer/LWT"
    qos: 1
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Washer Energy Today"
    state_topic: "tele/washer/SENSOR"
    value_template: "{{ value_json['ENERGY'].Today }}"
    unit_of_measurement: "kWh"
    availability_topic: "tele/washer/LWT"
    qos: 1
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Washer Energy Yesterday"
    state_topic: "tele/washer/SENSOR"
    value_template: "{{ value_json['ENERGY'].Yesterday }}"
    unit_of_measurement: "kWh"
    availability_topic: "tele/washer/LWT"
    qos: 1
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Washer Energy Total"
    state_topic: "tele/washer/SENSOR"
    value_template: "{{ value_json['ENERGY'].Total }}"
    unit_of_measurement: "kWh"
    availability_topic: "tele/washer/LWT"
    qos: 1
    payload_available: "Online"
    payload_not_available: "Offline"

input_boolean:
  washer:
    name: "Washer"
    initial: off
    icon: mdi:washing-machine
