---
- import_tasks: influxdb.yml
  tags:
    - influxdb

- import_tasks: watchtower.yml
  tags:
    - watchtower

- import_tasks: portainer.yml
  tags:
    - portainer

- import_tasks: grafana.yml
  tags:
    - grafana
