---
- name: create sonarr directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ hive_user }}"
    group: "{{ hive_user }}"
    mode: 0755
  with_items:
    - /docker/sonarr/config/
    - /tmp/downloads/completed

- name: create sonarr config
  template:
    src: sonarr-config.xml.j2
    dest: /docker/sonarr/config/config.xml
    owner: "{{ hive_user }}"
    group: "{{ hive_user }}"
    mode: 0644
  notify: restart sonarr

- name: sonarr Docker Container
  docker_container:
    name: sonarr
    image: linuxserver/sonarr
    pull: true
    volumes:
      - /docker/sonarr/config:/config
      - /tmp/downloads/completed:/downloads
      - /docker/shared:/shared
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ nas_mount_folder }}/TV Shows:/tv"
    ports:
      - "{{ sonarr_webui_port }}:8989/tcp"
    env:
      TZ: "{{ timezone }}"
      PUID: "{{ hive_uid | string }}"
      PGID: "{{ hive_gid | string }}"
    restart_policy: unless-stopped

- name: Add sonarr to network
  docker_network:
    name: hive
    connected:
      - sonarr
    appends: yes
