---
- name: watchtower Docker Container
  docker_container:
    name: watchtower
    image: v2tec/watchtower
    pull: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 4 * * *" --cleanup
    env:
      TZ: "{{ timezone }}"
      PUID: "{{ hive_uid | string }}"
      PGID: "{{ hive_gid | string }}"
    restart_policy: unless-stopped
